-- CREATE DATABASE HotelSanCarlosCompras CHARACTER SET UTF8;
USE HotelSanCarlosCompras;

-- TABLAS

CREATE TABLE ORDEN_COMPRA_ENCABEZADO(
	ID_ORDEN_COMPRA_ENCABEZADO int(16) not null,
    ESTADO		INT(1) NOT NULL, 
    FECHA_EMISION 	datetime NOT NULL,
    FECHA_REVISION  datetime NOT NULL,
    NOMBRE			varchar(20),
    DESCRIPCION 	varchar(100),
    FECHA_ESTIMADA_ENTREGA  datetime
);

CREATE TABLE ORDEN_COMPRA_DETALLE(
	ID_ORDEN_COMPRA_ENCABEZADO int(16) not null,
	ID_ORDEN_COMPRA_DETALLE int(16) not null,
    ID_PRODUCTO_ENCABEZADO INT(16),
    ID_PROVEEDOR INT(16),
    PRECIO_UNITARIO	FLOAT(4,2),
    CANTIDAD_PRODUCTO INT(3)
);

CREATE TABLE BODEGUA (
	ID_BODEGUA	INT(16),
    ID_SUCURSAL INT(16),
    DIRECCION VARCHAR(20),
    MAX_STOCK INT(3),
    MIN_STOCK INT(3),
    NOMBRE VARCHAR(20),
    DESCRIPCION VARCHAR(100),
    ESTADO INT (1)
);

CREATE TABLE PRODUCTO_ENCABEZADO(
    ID_PRODUCTO_ENCABEZADO INT(16),
    NOMBRE 	VARCHAR(20),
    DESCRIPCION VARCHAR(100)
);

CREATE TABLE PRODUCTO_DETALLE(
    ID_PRODUCTO_ENCABEZADO INT(16),
    ID_PRODUCTO_DETALLE INT(16),
	ID_PROVEEDOR	INT (16),
    ID_BODEGUA INT(16),
    STOCK	INT(3),
    MIN_STOCK INT(3),
    MAX_STOCK INT(3)
);

CREATE TABLE SUCURSAL (
	ID_SUCURSAL INT(16),
    NOMBRE VARCHAR(20)
);

CREATE TABLE PROVEEDOR(
	ID_PROVEEDOR	INT (16),
    NOMBRE VARCHAR(20),
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(20),
    ID_CONTACTO INT(16),
    PAGINA VARCHAR(20)
);

CREATE TABLE CONTACTO(
	ID_CONTACTO INT(16),
    NOMBRE VARCHAR(20),
    TELEFONO VARCHAR(16),
    EMAIL VARCHAR(20)
);

-- LLAVES PRIMARIAS
ALTER TABLE ORDEN_COMPRA_ENCABEZADO ADD CONSTRAINT ORDEN_COMPRA_ENCABEZADO_PK PRIMARY KEY (ID_ORDEN_COMPRA_ENCABEZADO);
ALTER TABLE ORDEN_COMPRA_DETALLE ADD CONSTRAINT ORDEN_COMPRA_DETALLE_PK PRIMARY KEY (ID_ORDEN_COMPRA_ENCABEZADO, ID_ORDEN_COMPRA_DETALLE, ID_PRODUCTO_ENCABEZADO, ID_PROVEEDOR);
ALTER TABLE BODEGUA ADD CONSTRAINT BODEGUA_PK PRIMARY KEY (ID_BODEGUA);
ALTER TABLE PRODUCTO_ENCABEZADO ADD CONSTRAINT PRODUCTO_ENCABEZADO_PK PRIMARY KEY (ID_PRODUCTO_ENCABEZADO);
ALTER TABLE PRODUCTO_DETALLE ADD CONSTRAINT PRODUCTO_DETALLE_ID PRIMARY KEY (ID_PRODUCTO_ENCABEZADO, PRODUCTO_DETALLE);
ALTER TABLE SUCURSAL ADD CONSTRAINT SUCURSAL_PK PRIMARY KEY (ID_SUCURSAL);
ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY (ID_PROVEEDOR);
ALTER TABLE CONTACTO ADD CONSTRAINT CONTACTO_PK PRIMARY KEY (ID_CONTACTO);

-- LLAVES FORANEAS
ALTER TABLE ORDEN_COMPRA_DETALLE ADD CONSTRAINT ORDEN_COMPRA_DETALLE_ORDEN_COMPRA_ENCABEZADO FOREIGN KEY (ID_ORDEN_COMPRA_ENCABEZADO) REFERENCES ORDEN_COMPRA_ENCABEZADO(ID_ORDEN_COMPRA_ENCABEZADO);
ALTER TABLE ORDEN_COMPRA_DETALLE ADD CONSTRAINT ORDEN_COMPRA_DETALLE_PRODUCTO_ENCABEZADO FOREIGN KEY (ID_PRODUCTO_ENCABEZADO) REFERENCES PRODUCTO_ENCABEZADO(ID_PRODUCTO_ENCABEZADO);
ALTER TABLE ORDEN_COMPRA_DETALLE ADD CONSTRAINT ORDEN_COMPRA_DETALLE_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE BODEGUA ADD CONSTRAINT BODEGUA_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL);

ALTER TABLE PRODUCTO_DETALLE ADD CONSTRAINT PRODUCTO_DETALLE_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);
ALTER TABLE PRODUCTO_DETALLE ADD CONSTRAINT PRODUCTO_DETALLE_BODEGUA FOREIGN KEY (ID_BODEGUA) REFERENCES BODEGUA(ID_BODEGUA);

ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_CONTACTO FOREIGN KEY (ID_CONTACTO) REFERENCES CONTACTO(ID_CONTACTO);
